sudo: false
language: ruby
script:
  - bundle exec rake
env:
  - SOLIDUS_BRANCH=v1.4 DB=mysql
  - SOLIDUS_BRANCH=v2.0 DB=mysql
  - SOLIDUS_BRANCH=v2.1 DB=mysql
  - SOLIDUS_BRANCH=v2.2 DB=mysql
  - SOLIDUS_BRANCH=v2.3 DB=mysql
  - SOLIDUS_BRANCH=v2.4 DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql
  - SOLIDUS_BRANCH=v1.4 DB=postgres
  - SOLIDUS_BRANCH=v2.0 DB=postgres
  - SOLIDUS_BRANCH=v2.1 DB=postgres
  - SOLIDUS_BRANCH=v2.2 DB=postgres
  - SOLIDUS_BRANCH=v2.3 DB=postgres
  - SOLIDUS_BRANCH=v2.4 DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
rvm:
  - 2.3.4
